export const ALL_MOVIES_REQUEST = 'ALL_MOVIES_REQUEST'
export const ALL_MOVIES_SUCCESS = 'ALL_MOVIES_SUCCESS'
export const ALL_MOVIES_FAIL = 'ALL_MOVIES_REQUEST'

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_REQUEST'

export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAIL = 'ADD_MOVIE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'